export const dataArr = [{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },
{ name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" }, { name: "P" },]